### ISSUE TITLE
开启READER_APP_SECURE, webdav无法登陆

### ISSUE THREAD

**Issue by lmingzhi** [hectorqin/reader#107]
用已注册用户，无法登陆webdav
default/123456 也无效

docker reader 版本：
v2.0.0-05161434

配置文件：

```yaml
version: '3.1'
services:

# reader 在线阅读
# 本人在线演示(服务器位于日本) : https://reader.nxnow.online(此域名7月过期)更换为 https://read.nxnow.top
# 在线演示测试账号/密码分别为guest/guest123,也可自行创建账号添加书源
# 书源参考 : https://github.com/NZESupB/ReadSource,书源合集下选一个合集进入网页后, Ctrl+S 保存至本地后导入网站即可,或者点击远程书源,将链接导入即可

#docker run -d --restart=always --name=reader -e "SPRING_PROFILES_ACTIVE=prod" -v $(pwd)/logs:/logs -v $(pwd)/storage:/storage -p 8080:8080 hectorqin/reader
# 多用户版
#docker run -d --restart=always --name=reader -v $(pwd)/logs:/logs -v $(pwd)/storage:/storage -p 8080:8080 hectorqin/reader java -jar /app/bin/reader.jar --spring.profiles.active=prod --reader.app.secure=true --reader.app.secureKey=管理密码 --reader.app.inviteCode=注册邀请码
# 多用户版 使用环境变量
#docker run -d --restart=always --name=reader -e "SPRING_PROFILES_ACTIVE=prod" -e "READER_APP_SECURE=true" -e "READER_APP_SECUREKEY=管理密码" -e "READER_APP_INVITECODE=注册邀请码" -v $(pwd)/logs:/logs -v $(pwd)/storage:/storage -p 8080:8080 hectorqin/reader

# 自用版
#  read_own:
#    image: hectorqin/reader
#    container_name: reader_own
#    restart: always
#    ports:
#      - 4395:8080
#    volumes:
#      - /home/reader/logs:/logs
#      - /home/reader/storage:/storage
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - READER_APP_CACHECHAPTERCONTENT=true #是否开启缓存章节内容 V2.0
# 多用户版
  read_all:
    image: hectorqin/reader
    container_name: reader #容器名 可自行修改
    restart: always
    ports:
      - 8080:8080 #4396端口映射可自行修改
    volumes:
      - /opt/reader/logs:/logs #log映射目录 /home/reader/logs 映射目录可自行修改
      - /opt/reader/storage:/storage #数据映射目录 /home/reader/storage 映射目录可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_SECURE=true #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_CACHECHAPTERCONTENT=true #是否开启缓存章节内容 V2.0
      - READER_APP_SECUREKEY="xxx"  #管理员密码  可自行修改
      - READER_APP_INVITECODE=xxx #注册邀请码,如需要取消注释 可自行修改
      - READER_APP_PROXY=false                # 是否使用代理
      - READER_APP_PROXYTYPE="HTTP"            # 代理类型
      - READER_APP_PROXYHOST="192.168.5.99"  # 代理 HOST
      - READER_APP_PROXYPORT="7890"            # 代理 PORT


# 自动更新docker
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    # 环境变量,设置为上海时区
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: reader watchtower --cleanup --schedule "0 0 4 * * *"
    # 仅更新reader与watchtower容器,如需其他自行添加 '容器名' ,如:reader watchtower redis
    # --cleanup 更新后清理旧版本镜像
    # --schedule 自动检测更新 crontab定时(限定6位crontab) 此处代表凌晨4点整
```

<img width="891" alt="image" src="https://user-images.githubusercontent.com/25837153/168721030-8dd16295-c1e8-46ed-8760-54a12b1d338f.png">
