### ISSUE TITLE
最新版启动失败

### ISSUE THREAD

**Issue by ctaoist** [hectorqin/reader#231]
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'reader.app.cache-chapter-content' to boolean:

    Property: reader.app.cache-chapter-content
    Value: true - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050
    Origin: System Environment Property "READER_APP_CACHECHAPTERCONTENT"
    Reason: failed to convert java.lang.String to boolean

Action:

Update your application's configuration

这个配置在你文档中还是boolean的吧，是不是哪里没更新过来

**Comment by ctaoist** [comment]
`java -jar reader-pro-2.7.1.jar`，docker compose文件：`READER_APP_CACHECHAPTERCONTENT=true`

**Comment by ctaoist** [comment]
```yaml
services:
  reader:
    image: openjdk:17-jdk-slim-buster
    container_name: reader3
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - default
    volumes:
      - /home/reader/logs:/logs #log映射目录 /home/reader/logs 映射目录可自行修改
      - /home/reader/storage:/storage #数据映射目录 /home/reader/storage 映射目录可自行修改
      - /home/reader:/reader # jar 所在目录
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=50 #用户上限,默认50
      - READER_APP_USERBOOKLIMIT=200 #用户书籍上限,默认200
      - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容 V2.0
      - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050 #开启远程webview
      - READER_APP_SECURE=true #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_SECUREKEY=adminpwd  #管理员密码  建议修改
      - READER_APP_INVITECODE=registercode #注册邀请码 建议修改,如不需要可注释或删除
    command: java -jar reader-pro-2.7.1.jar
```

环境变量部分抄的你仓库里的
