### ISSUE TITLE
[web/server] docker compose部署 out of memory

### ISSUE THREAD

**Issue by Dnine7** [hectorqin/reader#670]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
   docker compose部署 docker启动时报错
```
library initialization failed - unable to allocate file descriptor table - out of memory11:49:36.914 [main] INFO com.htmake.reader.ReaderApplication - Starting application with args: []
```
  机器内存16G
```
dnine7@dnine7-GL63-8RE:~/reader$ free -h
               total        used        free      shared  buff/cache   available
内存：          14Gi       4.9Gi       9.3Gi       265Mi       1.3Gi        10Gi
交换：         4.0Gi          0B       4.0Gi
```

**版本说明**
 - OS: [e.g. win]  说明操作系统   ubuntu 24.10
 - Deploy Method 说明软件部署方式  docker compose
 - Program Version 说明软件版本 3.2.14 

**docker-compose-yaml**
```
version: '3.1'
services:
# reader 在线阅读
# 公开服务器(服务器位于日本)：[https://reader.nxnow.top](https://reader.nxnow.top) 测试账号/密码分别为guest/guest123，也可自行创建账号添加书源，不定期删除长期未登录账号(2周)
# 书源集合 : [https://legado.aoaostar.com/](https://legado.aoaostar.com/) 点击打开连接，添加远程书源即可
# 公众号汇总 : [https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MjM5MzMyMDgyMA==&action=getalbum&album_id=2397535253763801090#wechat_redirect](https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MjM5MzMyMDgyMA==&action=getalbum&album_id=2397535253763801090#wechat_redirect)
# 手动更新方式 : docker-compose pull && docker-compose up -d
  reader:
    image: hectorqin/reader:latest
    #image: hectorqin/reader:openj9-latest #docker镜像，arm64架构或小内存机器优先使用此镜像.启用需删除上一行
    container_name: reader #容器名 可自行修改
    restart: always
    ports:
      - 9970:8080 #4396端口映射可自行修改
    networks:
      - share_net
    volumes:
      - /home/dnine7/reader/logs:/logs #log映射目录 /home/reader/logs 映射目录可自行修改
      - /home/dnine7/reader/storage:/storage #数据映射目录 /home/reader/storage 映射目录可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=999999 #用户上限,默认50
      - READER_APP_USERBOOKLIMIT=99999 #用户书籍上限,默认200
      - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容 V2.0
      # 如果启用远程webview，需要取消注释下面的 remote-webview 服务
     # - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050 #开启远程webview
      # 下面都是多用户模式配置
      - READER_APP_SECURE=true #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_SECUREKEY=xzq521xzq  #管理员密码  建议修改
      - READER_APP_INVITECODE=Dnine7 #注册邀请码 建议修改,如不需要可注释或删除
 # remote-webview:
  #  image: hectorqin/remote-webview
   # container_name: remote-webview #容器名 可自行修改
  #  restart: always
   # ports:
    #  - 8050:8050
   # networks:
   #   - share_net
# 自动更新docker镜像
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    # 环境变量,设置为上海时区
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: reader watchtower --cleanup --schedule "0 0 4 * * *"
    networks:
      - share_net
    # 仅更新reader与watchtower容器,如需其他自行添加 '容器名' ,如:reader watchtower nginx
    # --cleanup 更新后清理旧版本镜像
    # --schedule 自动检测更新 crontab定时(限定6位crontab) 此处代表凌晨4点整
networks:
  share_net:
    driver: bridge
```
